### ISSUE TITLE
EMODnet Chemistry: incomplete dataset?

### ISSUE THREAD

**Issue by ctroupin** [maris-development/beacon-blue-cloud#4]
## Description

I'm testing the EMODnet Chemistry beacon instance, but for regions such as the Mediterranean, we get a `204` response i.e. no data in the region of interest (while there should be).

## How to reproduce?

Here is an example where I query all the phosphate data from 1960 to 2000 for the World Ocean. The figure below shows the positions of the observations. 

Notes
* I tested with longitudes until 360°E, just in case the coordinates are not between -180° and 180°.
* Similar results for other variables such as oxygen concentration. 

It looks like only the North Atlantic region is available (maybe it's on purpose, in that case the issue can be closed)

```
import requests
import json
import datetime

dateref = datetime.date(1921, 1, 1) #Days since 1921
mintemp = datetime.date(1960, 1, 1)
maxtemp = datetime.date(2000, 1, 1)
mintemporal = (mintemp - dateref).days #Days since 1921
maxtemporal = (maxtemp - dateref).days #Days since 1921

query = {'query_parameters': [{'column_name': 'Water_body_phosphate',
   'alias': 'Water_body_phosphate'},
  {'column_name': 'date_time', 'alias': 'TIME'},
  {'column_name': 'Depth', 'alias': 'DEPTH'},
  {'column_name': 'longitude', 'alias': 'LONGITUDE'},
  {'column_name': 'latitude', 'alias': 'LATITUDE'}],
 'filters': [{'for_query_parameter': 'TIME', 'min': mintemporal, 'max': maxtemporal},
  {'for_query_parameter': 'DEPTH', 'min': 0, 'max': 20},
  {'for_query_parameter': 'LONGITUDE', 'min': -180, 'max': 360},
  {'for_query_parameter': 'LATITUDE', 'min': -90, 'max': 90.},
  {'for_query_parameter': 'Water_body_phosphate',
   'min': 0,
   'max': 500}],
 'output': {'format': 'netcdf'}}

response = requests.post("https://beacon-emod-chem.maris.nl/api/query", json.dumps(query), headers = {
    'Authorization' : f'Bearer {Token}',
    'Content-type': 'application/json'
})
```

### Phosphate observations (1960-2000)
![Water_body_phosphate_1960_2000](https://github.com/user-attachments/assets/ae63d59a-ef23-4375-9785-ecdb651e8962)

**Comment by sharppaul** [comment]
Hi Charles,

This subset is what was requested by the Blue-Cloud 2026 WB2 (EMODnet Chemistry North East Atlantic Collection).

So this is intended. I'll add this information to the page where the beacon instances are listed in the DD&AS https://data.blue-cloud.org/search

Kind regards,

Paul

**Comment by ctroupin** [comment]
Thanks Paul, that totally makes sense!
